import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';
import { ReactQueryClientProvider } from '@/components/QueryClientProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReactQueryClientProvider>
			<html lang='en' className='dark'>
				{/* <html lang='en'> */}
				<body>
					<Sidebar />
					{children}
					<Footer />
				</body>
			</html>
		</ReactQueryClientProvider>
	);
}
